name: Maven Package Deployment

on:
  push:
    branches:
      - main   # This runs when code is pushed to the main branch
  pull_request:
    branches:
      - main   # This runs on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Runs on an Ubuntu environment
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # Version of Java
          distribution: 'temurin'   # AdoptOpenJDK
          server-id: github          # ID for GitHub server
          settings-path: ~/.m2       # Path to Maven settings
      
      # Step 3: Create the Maven settings.xml for authentication
      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOL
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>Roshini-11</username>
                <password>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</password>
              </server>
            </servers>
          </settings>
          EOL

      # Step 4: Verify directory structure
      - name: Verify Directory and Check Files
        run: |
          pwd

      # Step 5: Build and test the project
      - name: Build and Test
        run: mvn clean install
        working-directory: .   # This ensures Maven runs in the root directory where pom.xml is located

      # Step 6: Publish the package to GitHub Packages
      - name: Publish Package to GitHub Packages
        run: mvn deploy -X
        working-directory: .   # This ensures Maven deploys from the root directory where pom.xml is located
        env:
          GITHUB_TOKEN: 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   # GitHub token for authentication
